all: challenge solver

challenge: challenge.c
	gcc -o challenge challenge.c -Wall

solver: solver.c
	gcc -o solver solver.c -Wall

clean:
	rm -f challenge solver

run_challenge:
	./challenge

solve:
	./solver
